//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        internal static string AccountInfor {
            get {
                return ResourceManager.GetString("AccountInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng kế toán.
        /// </summary>
        internal static string AccountingDept {
            get {
                return ResourceManager.GetString("AccountingDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại sản phẩm.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm công trình.
        /// </summary>
        internal static string AddConstruction {
            get {
                return ResourceManager.GetString("AddConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tin tức.
        /// </summary>
        internal static string AddNews {
            get {
                return ResourceManager.GetString("AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tin tức/sự kiện.
        /// </summary>
        internal static string AddNewsEvent {
            get {
                return ResourceManager.GetString("AddNewsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tin khuyến mãi.
        /// </summary>
        internal static string AddPromotion {
            get {
                return ResourceManager.GetString("AddPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tuyển dụng.
        /// </summary>
        internal static string AddRecruitment {
            get {
                return ResourceManager.GetString("AddRecruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ: 183 Hoa Bằng - Yên Hòa - Cầu Giấy - Hà Nội.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong kho còn hàng.
        /// </summary>
        internal static string AvailableInStore {
            get {
                return ResourceManager.GetString("AvailableInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại sản phẩm.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đỗi mật khẩu.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công..
        /// </summary>
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh Công Trình.
        /// </summary>
        internal static string ConstructionImages {
            get {
                return ResourceManager.GetString("ConstructionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản Quyền.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới tài khỏan.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa loại sản phẩm.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tin tức.
        /// </summary>
        internal static string EditNew {
            get {
                return ResourceManager.GetString("EditNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa tin tức/sự kiện.
        /// </summary>
        internal static string EditNewsEvent {
            get {
                return ResourceManager.GetString("EditNewsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa sản phẩm.
        /// </summary>
        internal static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa tin khuyến mãi.
        /// </summary>
        internal static string EditPromotion {
            get {
                return ResourceManager.GetString("EditPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình hiện tại.
        /// </summary>
        internal static string EmageCurrent {
            get {
                return ResourceManager.GetString("EmageCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong kho hết hàng.
        /// </summary>
        internal static string EmptyInStore {
            get {
                return ResourceManager.GetString("EmptyInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả tiếng Anh.
        /// </summary>
        internal static string ENDescription {
            get {
                return ResourceManager.GetString("ENDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tiếng Anh.
        /// </summary>
        internal static string ENName {
            get {
                return ResourceManager.GetString("ENName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thông tin liên hệ.
        /// </summary>
        internal static string EnterContactInfo {
            get {
                return ResourceManager.GetString("EnterContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có khuyến mãi.
        /// </summary>
        internal static string IsPromoted {
            get {
                return ResourceManager.GetString("IsPromoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết website.
        /// </summary>
        internal static string LinkedWebsites {
            get {
                return ResourceManager.GetString("LinkedWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Login1 {
            get {
                return ResourceManager.GetString("Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập.
        /// </summary>
        internal static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập.
        /// </summary>
        internal static string LoginInfo1 {
            get {
                return ResourceManager.GetString("LoginInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        internal static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bởi:.
        /// </summary>
        internal static string LogonBy {
            get {
                return ResourceManager.GetString("LogonBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban giám đôc.
        /// </summary>
        internal static string ManagementBoard {
            get {
                return ResourceManager.GetString("ManagementBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng marketing.
        /// </summary>
        internal static string MarketingDept {
            get {
                return ResourceManager.GetString("MarketingDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hộp thư.
        /// </summary>
        internal static string MessageBox {
            get {
                return ResourceManager.GetString("MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức - Sự Kiện.
        /// </summary>
        internal static string NewsEvent {
            get {
                return ResourceManager.GetString("NewsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tiếp.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có chủ đề.
        /// </summary>
        internal static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cập nhật.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tiêu đề.
        /// </summary>
        internal static string NoTitle {
            get {
                return ResourceManager.GetString("NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không khuyến mãi.
        /// </summary>
        internal static string NotPromoted {
            get {
                return ResourceManager.GetString("NotPromoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ online.
        /// </summary>
        internal static string OnlineSupport {
            get {
                return ResourceManager.GetString("OnlineSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm.
        /// </summary>
        internal static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sản phẩm.
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại sản phẩm.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi.
        /// </summary>
        internal static string Promoted {
            get {
                return ResourceManager.GetString("Promoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức Khuyến Mãi.
        /// </summary>
        internal static string PromotionProgram {
            get {
                return ResourceManager.GetString("PromotionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển Dụng.
        /// </summary>
        internal static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ mật khẩu.
        /// </summary>
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng kinh doanh.
        /// </summary>
        internal static string SaleDept {
            get {
                return ResourceManager.GetString("SaleDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả ngắn.
        /// </summary>
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng kỹ thuật.
        /// </summary>
        internal static string TechnicalDept {
            get {
                return ResourceManager.GetString("TechnicalDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đến.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọai.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọai sản phẩm.
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản không thành công..
        /// </summary>
        internal static string ValidateCreateAccount {
            get {
                return ResourceManager.GetString("ValidateCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã tồn tại trong hệ thông. Xin nhập email khác..
        /// </summary>
        internal static string ValidateDuplicateEmail {
            get {
                return ResourceManager.GetString("ValidateDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng đã tồn tại trong hệ thống. Xin nhập tên người dùng khác..
        /// </summary>
        internal static string ValidateDuplicateUserName {
            get {
                return ResourceManager.GetString("ValidateDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập email..
        /// </summary>
        internal static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập mật khẩu..
        /// </summary>
        internal static string ValidatePassword {
            get {
                return ResourceManager.GetString("ValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới và xác nhận mật khẩu không đồng nhất..
        /// </summary>
        internal static string ValidatePasswordConfirmPassword {
            get {
                return ResourceManager.GetString("ValidatePasswordConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập tên người dùng..
        /// </summary>
        internal static string ValidateUserName {
            get {
                return ResourceManager.GetString("ValidateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả tiếng Việt.
        /// </summary>
        internal static string VNDescription {
            get {
                return ResourceManager.GetString("VNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tiêng Việt.
        /// </summary>
        internal static string VNName {
            get {
                return ResourceManager.GetString("VNName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng hoặc mật khẩu không chính xác..
        /// </summary>
        internal static string WarningLogonUnssucessful {
            get {
                return ResourceManager.GetString("WarningLogonUnssucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 6 kí tự.
        /// </summary>
        internal static string WarningPasswordLength {
            get {
                return ResourceManager.GetString("WarningPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hành.
        /// </summary>
        internal static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên của bạn.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
