<?xml version="1.0" encoding="utf-8"?>
<Database Name="Library" Class="ABDH_DemoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DUONG-D9EB8AEE5\SQLEXPRESS;Initial Catalog=Library;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblDinhKem" Member="tblDinhKems">
    <Type Name="tblDinhKem">
      <Column Name="DinhKemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaiLieuDinhKemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblDinhKem" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserGroup" Member="tblUserGroups">
    <Type Name="tblUserGroup">
      <Column Name="UserGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserGroupName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupStatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="tblUserGroup_tblPermission" Member="tblPermissions" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="tblPermission" />
      <Association Name="tblUserGroup_tblUser" Member="tblUsers" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="tblUser" />
    </Type>
  </Table>
  <Table Name="dbo.tblDocument" Member="tblDocuments">
    <Type Name="tblDocument">
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocumentType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DocSize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ReferrenceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UploadedDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Extension" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblDocument" Member="tblTaiLieu" ThisKey="ReferrenceID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblGui" Member="tblGuis">
    <Type Name="tblGui">
      <Column Name="GuiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Chieu" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblGui" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" />
      <Association Name="tblUser_tblGui" Member="tblUser" ThisKey="UserID" OtherKey="UserID" Type="tblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblNews" Member="tblNews">
    <Type Name="tblNew">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblNgonNgu" Member="tblNgonNgus">
    <Type Name="tblNgonNgu">
      <Column Name="NgonNguID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNgonNgu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblNgonNguTL" Member="tblNgonNguTLs">
    <Type Name="tblNgonNguTL">
      <Column Name="NgonNguTLID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNgonNgu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblNgonNguTL" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblNhomTaiLieu" Member="tblNhomTaiLieus">
    <Type Name="tblNhomTaiLieu">
      <Column Name="NhomTaiLieuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhomTaiLieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenNhomTaiLieu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="tblNhomTaiLieu_tblTaiLieu" Member="tblTaiLieus" ThisKey="NhomTaiLieuID" OtherKey="NhomTaiLieuID" Type="tblTaiLieu" />
    </Type>
  </Table>
  <Table Name="dbo.tblPage" Member="tblPages">
    <Type Name="tblPage">
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PageDesc" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="tblPage_tblPermission" Member="tblPermissions" ThisKey="PageID" OtherKey="PageID" Type="tblPermission" />
    </Type>
  </Table>
  <Table Name="dbo.tblPermission" Member="tblPermissions">
    <Type Name="tblPermission">
      <Column Name="PermissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ViewRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InsertRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UpdateRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ApproveRight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tblPage_tblPermission" Member="tblPage" ThisKey="PageID" OtherKey="PageID" Type="tblPage" IsForeignKey="true" />
      <Association Name="tblUserGroup_tblPermission" Member="tblUserGroup" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="tblUserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPhanDoan" Member="tblPhanDoans">
    <Type Name="tblPhanDoan">
      <Column Name="PhanDoanID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhanDoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MoTaChung" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhanDoan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblPhanDoan" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTacGia" Member="tblTacGias">
    <Type Name="tblTacGia">
      <Column Name="TacGiaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblTacGia" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblTaiLieu" Member="tblTaiLieus">
    <Type Name="tblTaiLieu">
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="VongDoi_StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VongDoi_EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TomTatNoiDung" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SoLanXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhomTaiLieuID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThaiTaiLieu" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TacGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgonNgu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TuKhoa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblDinhKem" Member="tblDinhKems" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblDinhKem" />
      <Association Name="tblTaiLieu_tblDocument" Member="tblDocuments" ThisKey="TaiLieuID" OtherKey="ReferrenceID" Type="tblDocument" />
      <Association Name="tblTaiLieu_tblGui" Member="tblGuis" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblGui" />
      <Association Name="tblTaiLieu_tblNgonNguTL" Member="tblNgonNguTLs" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblNgonNguTL" />
      <Association Name="tblTaiLieu_tblPhanDoan" Member="tblPhanDoans" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblPhanDoan" />
      <Association Name="tblTaiLieu_tblTacGia" Member="tblTacGias" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTacGia" />
      <Association Name="tblTaiLieu_tblThaoTac" Member="tblThaoTacs" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblThaoTac" />
      <Association Name="tblTaiLieu_tblTrangThai" Member="tblTrangThais" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTrangThai" />
      <Association Name="tblTaiLieu_tblTuKhoa" Member="tblTuKhoas" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTuKhoa" />
      <Association Name="tblNhomTaiLieu_tblTaiLieu" Member="tblNhomTaiLieu" ThisKey="NhomTaiLieuID" OtherKey="NhomTaiLieuID" Type="tblNhomTaiLieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblThaoTac" Member="tblThaoTacs">
    <Type Name="tblThaoTac">
      <Column Name="ThaoTacID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HanhVi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblThaoTac" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="tblUser_tblThaoTac" Member="tblUser" ThisKey="UserID" OtherKey="UserID" Type="tblUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTrangThai" Member="tblTrangThais">
    <Type Name="tblTrangThai">
      <Column Name="TrangThaiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblTrangThai" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblTuKhoa" Member="tblTuKhoas">
    <Type Name="tblTuKhoa">
      <Column Name="TuKhoaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaiLieuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TuKhoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblTaiLieu_tblTuKhoa" Member="tblTaiLieu" ThisKey="TaiLieuID" OtherKey="TaiLieuID" Type="tblTaiLieu" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblUser" Member="tblUsers">
    <Type Name="tblUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserStatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FailedLogin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsEmployee" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblUser_tblGui" Member="tblGuis" ThisKey="UserID" OtherKey="UserID" Type="tblGui" />
      <Association Name="tblUser_tblThaoTac" Member="tblThaoTacs" ThisKey="UserID" OtherKey="UserID" Type="tblThaoTac" />
      <Association Name="tblUserGroup_tblUser" Member="tblUserGroup" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="tblUserGroup" IsForeignKey="true" />
    </Type>
  </Table>
</Database>